### PR TITLE
Add extension that overloads plus with merge and allow transformation of nullables to empty.

### PR DESCRIPTION
**Pull request by sbuettner**

### CODE REVIEW

**Comment by dynaxis** [comment]
I'm not sure if `mergeWith` deserves the `plus` operator. There are `mergeSequential` and `concatWith` which do similar but subtly different jobs. What makes `mergeWith` any special than them?

**Comment by sbuettner** [comment]
@dynaxis Thanks for your question. The idea is that `+` is a commutative operator where the order of the operands has no impact on the result. This is not the case for `concatWith` where the order of the operands defines the order of the output of the individual items of the observables.

A merged observable allows interleaving of the outputs and therefore makes no assumptions about the order of the operands which from my point of view resembles the `+` operator.

**Comment by dynaxis** [comment]
@sbuettner Thanks you. Got your point. But even in Kotlin's standard library, there are cases where `plus` is not commutative (e.g. `Iterable<T>.plus(Iterable<T>)`). So that alone doesn't seem so compelling reason to use `plus` operator here, IMHO. And I'm not sure `mergeWith` is generally more frequently used than the others. That's it. :)

**Comment by sbuettner** [comment]
@dynaxis You are right. Since `Iterable<T>.plus(Iterable<T>)` returns a `List` which is ordered by definition there no simple way to make it commutative and therefore its the least surprise.

**Comment by sbuettner** [comment]
@sdeleuze Any feedback on this?

**Comment by sdeleuze** [comment]
I think your discussion with @dynaxis shows that there is different ways of adding 2 `Flux` or `Mono` and I am not sure there is an obvious one. That's why I am not very keen of introducing this kind of opinionated extension in `reactor-kotlin-extensions`.

For `Flux<T>?.orEmpty()` I admit I have not seen this use case yet, so I am not sure this is a frequent one. The pattern I have mostly seen is that `Mono` and `Flux` are non-nullable containers which could complete without any value to express the equivalent of `null` blocking behavior. What is your use case for that?

**Comment by sbuettner** [comment]
1.  You are right that there are different ways although I still think that adding is still something different than concatenating 😄 
2. Just syntactic sugar: `orEmpty` is inspired by kotlins `orEmpty` function for Strings to avoid the ternary operator.

**Pull request closed without merging**
